module.exports = {
  processors: ['stylelint-processor-styled-components'],
  extends: [
    'stylelint-config-recommended',
    'stylelint-config-styled-components',
  ],
  ignoreFiles: ['**/*.(ttf|txt|json|png|xml)'],
  rules: {
    'property-no-unknown': [
      true,
      {
        ignoreProperties: [
          'aspect-ratio',
          'border-bottom-end-radius',
          'border-bottom-start-radius',
          'border-end-width',
          'border-end-color',
          'border-start-color',
          'border-start-width',
          'border-top-end-radius',
          'border-top-start-radius',
          'elevation',
          'end',
          'include-font-padding',
          'margin-horizontal',
          'margin-end',
          'margin-start',
          'margin-vertical',
          'overlay-color',
          'padding-horizontal',
          'padding-end',
          'padding-start',
          'padding-vertical',
          'resizeMode',
          'text-align-vertical',
          'text-shadow-color',
          'text-shadow-offset',
          'text-shadow-radius',
          'tint-color',
          'writing-direction',
        ],
      },
    ],
  },
};
